# Generated by Django 4.2.13 on 2024-05-20 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('activity_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='activity_name',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='date',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.activity'),
        ),
    ]
