# Generated by Django 4.2.13 on 2024-05-20 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_activity_remove_activitylog_activity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logger.activity'),
        ),
    ]
